### ISSUE TITLE
Hello, similar renderer on development

### ISSUE THREAD

**Issue by a-lucas** [dai-shi/connect-prerenderer#23]
I am the main contributor of [ng1-server](https://github.com/ng-consult/ng1-server) and I read with attention your code base. I can see you are using jsodm - and funny enough, that is how I started to code ng1-server 10 months ago, but gave it up because of too many issues and unsupported features.

I reckon your project and mine are very similar, and I would like to get your opinion. Maybe we can join force?

What do you think?

**Comment by dai-shi** [comment]
@a-lucas Thanks for letting me know your project.
Both projects have something in similar, but `connect-prerenderer` is a simple jsdom wrapper with minimal code, whereas your project is specialized for angular1.
My project is rather old and I would keep it simple and only maintain for severe issues.
